### ISSUE TITLE
Model project question

### ISSUE THREAD

**Issue by ndc388** [NumEconCopenhagen/IntroProg-lectures#15]
Hi,

Regarding the model project there was a note put out that if you choose models we had previously worked with, you would have to make it more advanced.

We are some people who are only on the third semester of our bachelor and the Solow model is the only "real" model that we have worked with so far.

We were therefore wondering what this specifically entail? And how advanced would it have to be? 

Thank you in advance!

**Comment by AskerNC** [comment]
Hi
Thank you writing this question
If your starting model is one of the extended Solow models from Makro i (like endogenous growth, human capital, land or energy as input), then you are already clear of this note.
The note was to avoid projects that are extremely similar to the class material, without much original work.
If you choose to start with the base Solow model (I think it would be easier to start from an extended model), then the note entails that your own extension has to be a bit more advanced and significantly different/harder to solve than the base case

Hope this makes sense, otherwise let me know
