### ISSUE TITLE
Question 5

### ISSUE THREAD

**Issue by CarolineBergholdtH** [NumEconCopenhagen/IntroProg-lectures#6]
Hello,
We are in doubt what is expected of us in question 5.

Are we meant to add to the regression formula, or what does a extension of the model imply?

The data is the results we get by running the model right?

**Comment by AskerNC** [comment]
Hi
Thank you for your question. The formulation could maybe have been a bit more clear.
You are not meant to change the regression formula, you're are meant to change the theoretical model. 

'fit the data' and 'match the data' means that the model parameters should adjust to fit the real world, i.e.  $\beta_0=0.4$ and $\beta_1=-0.1$.  (let's call this real data) 

This is not the same data as the data that comes out from the model, which is the data that you run the regression using and get $\hat{\beta_{0}}$ and $\hat{\beta_{1}}$ from. (simulated data) 

So the question should maybe be that you are asked to change the model such that the simulated data will fit better when compared to the real data.

Changes to the model would be changes to the equations of the model. For example, adding something to the utility function, changing the production function, etc. 
Something a bit harder would be to add equations to the model.
I think some fun possible avenues would be the utility function: maybe households have non-rational preferences about who does household work? 
Something a bit harder would be how wages are obtained: Maybe wages are not constant but increasing in the number of hours worked? (This is harder because $w_{F}$ is part of the grid of coefficients you are using to simulate your data, so you need to still have one $w_{F}$ in your model, but maybe market consumption is not linear in $L_{M}$ and $L_{F}$?

It should be emphasized that your model extension does not have to make the fit to the real data better. If you make an attempt at an extension (and in words motivate why you think it will help) but find that you are not able to fit the real data when  $\alpha=0.5$, that is also a fine result.
